### ISSUE TITLE
Unexpected token S in JSON at position 4

### ISSUE THREAD

**Issue by smurfb** [OlivierZal/com.melcloud#17]
Hi!

Im trying to add a AIR to AIR heat pump. After I put in username and password it says searching for devices and then after a couple of seconds this error appear: "Unexpected token S in JSON at position 4". 

Am I doing something wrong? 

Thanks for your efforts!

**Comment by doinkmaster** [comment]
Smae issue here.

**Comment by doinkmaster** [comment]
Hi. I just made it work.
Instead of using the homey app on the phone i logged in to my.homey.app and did it from the web. There it worked perfectly.

**Comment by smurfb** [comment]
It worked for me aswell. Thanks for the suggestion!

Den mån 3 okt. 2022 16:06doinkmaster ***@***.***> skrev:

**Comment by OlivierZal** [comment]
Hi @smurfb and @doinkmaster, I'm happy everything works by now.

This error message appears when the device cannot be reached anymore, e.g. because permissions have been removed.

Don't hesitate to install this test version, which fixed several issues, in particular with flow cards: https://homey.app/a/com.mecloud/test/ and to tell me if you encounter any issue.

Best regards
