### ISSUE TITLE
Missing option in Then

### ISSUE THREAD

**Issue by Fred0172** [OlivierZal/com.melcloud#218]
Hi,
Hope you can assist me, I miss the option in the Then section of the flow to set the mode of the air-to-water 
There is an option to choose Operation mode but that gives me the options inside temp/fixed temp/ Wheater comp.
I was looking for to set the Operation Mode State for example Legionella/heating/SWW is that possible?

Thanks,
Fred

**Comment by OlivierZal** [comment]
Hi @Fred0172 

Unfortunately this action does not exist – in the same way it is not possible from the MELCloud mobile/web app.

That's because actually this "operation mode" is the _state_ of heat pump's _current_ operation, which depends on other conditions than the chosen "zone's _action_ (operation) mode" (fixed temp, compensation etc.). 

Sorry...

**Comment by Fred0172** [comment]
Olivier, Thanks for the update
