### ISSUE TITLE
Air-to-air heat pump reports power consumption when off

### ISSUE THREAD

**Issue by jgogstad** [OlivierZal/com.melcloud#272]
Thanks for contributing this integration, I use it every day, it's wonderful.

I've noticed that when I turn off my Mitsubishi Kaiteki air-to-air heat pump, via the Homey app, it still reports 700W power consumption in the homey zone power usage breakdown. It should (hopefully) be close to 0W.

**Comment by OlivierZal** [comment]
Hi @jgogstad,

Thanks for your feedback 😊

The problem is that the (official) MELCloud API does not provide live power consumption: this API refreshes a very approximative **energy** consumption (in kWh) only on an hourly basis, and from that I infer an (still approximative) **average power** consumption (in W) in the last hour. 

In particular that means that if you switch off your device less than 1 hour, you won’t see it neither in the official MELCloud nor in Homey, and if you switch it off more than 1 hour, you’ll see 1 hour later.
