### ISSUE TITLE
Flow card "Fan_Speed_Action" removed?

### ISSUE THREAD

**Issue by mainnsto** [OlivierZal/com.melcloud#29]
Not sure if this was done by intention, but my flows controlling fan speed on my heat pumps are now broken. 
Can you confirm if these cards have been changed permanently and i need to replace cards?

**Comment by OlivierZal** [comment]
Hi @mainnsto,

First of all, I'm sorry for the convenience.

As explained in the change logs I reshaped the whole app to use standard Homey features. 

So you'll have to change some flow cards because of that but I promise it's once and for all and won't change anymore!

Don't hesitate to ask for assistance if you don't succeed in fix some of your flows. 

Kind regards

**Comment by mainnsto** [comment]
Hi Olivier, 
Thanks for the fast reply, unfortunately I missed your note about this in the release notes. I will change my flow cards then, no problem :-) Just needed to be sure. Finally, thanks for maintaining a great functioning app! Had very little problems with it.
Best regards
