### ISSUE TITLE
External temperature sensor 

### ISSUE THREAD

**Issue by Githubthl** [OlivierZal/com.melcloud#312]
It would be great if the app supported the possibility to select another homey device as melclouds thermostat instead of using the internal.

**Comment by OlivierZal** [comment]
Hi @Githubthl,

As per Homey policy, it’s not possible to connect the API devices of a given brand to other devices within the app, except if it’s a native feature of this brand: I know because I already proposed a version of my app including external sensor selection, but it has been refused. 

Kind regards
