### ISSUE TITLE
power/energy

### ISSUE THREAD

**Issue by Jimsson1** [OlivierZal/com.melcloud#314]
I don't get values ​​for power & energy anymore. previously they worked fine
![Screenshot_2023-11-20-22-52-46-65_4bbfc4a7dd885a2bb189f300112a7ed4](https://github.com/OlivierZal/com.melcloud/assets/150896336/4b439e90-7b07-47ee-8881-38e867fa9316)

**Comment by OlivierZal** [comment]
Hi @Jimsson1, I cannot reproduce on my side. 

Can you please provide olivier.zalmanski@me.com with a guest access from the official MELCloud app or website, so I can investigate?

**Comment by OlivierZal** [comment]
Also, can you check you run the version 30.0.1 or above of the MELCloud Homey app?

**Comment by Jimsson1** [comment]
Yes, the app version is 30.1.0

**Comment by OlivierZal** [comment]
So I would need a guest access to your MELCloud.

For information I attach what I see on my side:

![IMG_F41B15AE8696-1](https://github.com/OlivierZal/com.melcloud/assets/88216225/78adc82b-5111-42ff-a631-bb0e51e61f0c)

**Comment by OlivierZal** [comment]
I notice that the labels displayed on your device doesn't come from my app: "för en timme sedan"...

**Comment by OlivierZal** [comment]
Thanks, I can reproduce with your device.

**Comment by OlivierZal** [comment]
Hi @Jimsson1, here is the result of my investigation.

I noticed that your MELCloud energy API broke between January 6 and 7 and has been down since then.

See attached screenshots, where you have energy values for January 6 but no more for January 7 (and the days after).

<img width="934" alt="January 6" src="https://github.com/OlivierZal/com.melcloud/assets/88216225/c245e805-9dba-46e1-b58b-1ad300d40b4c">

<img width="1228" alt="January 7" src="https://github.com/OlivierZal/com.melcloud/assets/88216225/57f78389-8489-40d9-a126-39545e83adab">

**Comment by OlivierZal** [comment]
Same on the official MELCloud app: if I generate an energy report for the period from January 1, there is no more value after January 6:

<img width="567" alt="On MELCloud" src="https://github.com/OlivierZal/com.melcloud/assets/88216225/461d3ead-63bc-49cb-ba23-2371e58b0a40">

So it's not a Homey issue but a MELCloud one...

**Comment by Jimsson1** [comment]
okay, is that something I should submit to melcloud support

**Comment by OlivierZal** [comment]
Yes, I think only they can fix the issue or advice, but be aware they might not be very responsive...
