### ISSUE TITLE
5.2.8

### ISSUE THREAD

**Issue by ronennieshow** [OlivierZal/com.melcloud#33]
Hi

I have some minor issues (for as far as i have been able to test the New app)

1. The refresh rate of the app is now limited to a minimum of 3 minuts. In the past this was 1 minut.
Problem for me is that i use the Hot water temperatuur for the color of my mirror lighting so i can see how long i can keep showering before the Hot water temperatuur wil drop

2. In the dashboard i can not select the Hot water tank temperatuur it is only visible on the pc in the bigger machine picture

**Comment by OlivierZal** [comment]
Hi @ronennieshow,

Knowing better the way the MELCloud, 3 minutes seem safer to avoid sync issues. But no problem, I will revert the minimum back to 1 minute in the next release. 

Concerning the second issue, can I have screenshots? Because water tank temperature has moved away from the dashboard to the dedicated temperature tab (but this should apply both to PC and mobile app, that's why I'm a bit lost). 

Best regards

**Comment by ronennieshow** [comment]
![image](https://user-images.githubusercontent.com/113858484/198059538-0bf680a8-ebad-4c8e-840c-630a3086f092.png)
The thirt line is for the tempreture of the warm water tank

![image](https://user-images.githubusercontent.com/113858484/198059881-0c923446-455c-4dea-859a-38d4c255e2ab.png)

But i can not see this value in this window. 
On a pc it is not a real big issue because you have the device picture with the value within
But on a phone i can not choose this option. 

Also i can not change the hot water setpoint temp any more in the settings menu

**Comment by OlivierZal** [comment]
Ok I understand better, it's because of the new capability design: both were moved and gathered under the dedicated temperature tab:

![image](https://user-images.githubusercontent.com/88216225/198063673-55e37805-77b4-48bb-9c1c-eb18600094a7.png)
![image](https://user-images.githubusercontent.com/88216225/198063697-3ec9fa4c-c151-4077-add5-118a5c2e8533.png)

For more explanations about this move: https://github.com/OlivierZal/com.melcloud/issues/30

**Comment by janhjordie** [comment]
@ronennieshow Just be aware of pulling data to often from MELCloud.
I have experienced after Mitsubishi added MSSQT to MELCloud for several months ago, and made my connection unstable because of to many request, and my requests was stacking up in the MSSQT queue

**Comment by OlivierZal** [comment]
@ronennieshow, it has just been released.
