### ISSUE TITLE
Bug after last update

### ISSUE THREAD

**Issue by kajo23** [OlivierZal/com.melcloud#371]
Bug after last update 
![image](https://github.com/OlivierZal/com.melcloud/assets/38912495/de3f49cd-e5c4-4df7-83e9-b256155a5a68)

**Comment by OlivierZal** [comment]
Can I have more context @kajo23? Because from the screenshot it seems you want to have both cooling and heating at the same time, what is not possible. 

The flow fails but does the direct commands work?

I invite you to provide olivier.zalmanski@me.com with a guest access from the official MELCloud app (https://app.melcloud.com > settings > guest access) so I can debug (because I have only an air-to-air device).

**Comment by OlivierZal** [comment]
I have an idea why it would have worked and why it doesn’t work anymore, but fact it doesn’t work anymore is rather part of an enhancement, because the action you seem to do shouldn’t happen, that’s why I need context.

**Comment by OlivierZal** [comment]
E.g. are you sure you’re device is not running in curve or room temperature operation mode?

**Comment by OlivierZal** [comment]
Can I have more context @kajo23?

E.g. because if your device is running in curve or room temperature operation mode, it’s normal that you don’t satisfy any of these 2 conditions.

I invite you to provide [olivier.zalmanski@me.com](mailto:olivier.zalmanski@me.com) with a guest access from the official MELCloud app (https://app.melcloud.com/ > settings > guest access) so I can debug (because I have only an air-to-air device).

**Comment by OlivierZal** [comment]
I think I've found the bug.

Can you provide [olivier.zalmanski@me.com](mailto:olivier.zalmanski@me.com) with a guest access from the official MELCloud app (https://app.melcloud.com/ > settings > guest access), so I can confirm the resolution? (because I have only an air-to-air device).

**Comment by OlivierZal** [comment]
This should fix: https://github.com/OlivierZal/com.melcloud/commit/3928c942934ea7eba508b8b380184b31c4802db6

**Comment by OlivierZal** [comment]
It’s already available in test version: https://homey.app/a/com.mecloud/test/

do you confirm it solves your issue?

**Comment by kajo23** [comment]
with last official update this issue is solved
