### ISSUE TITLE
Problems changing fan speed

### ISSUE THREAD

**Issue by marnygar** [OlivierZal/com.melcloud#383]
Hi
![Skjermbilde 2024-04-09 134522](https://github.com/OlivierZal/com.melcloud/assets/54357679/519540b2-a3bc-4ea4-98d2-e1a3e9048503)

When I have a folw to change the fan speed, I get the attached error message.
I think it has to do with the fact that it says "3.0", and not "3".
I can't remove the ".0" myself, as it's just a lever to pull to change the value on the card.

**Comment by OlivierZal** [comment]
Hi @marnygar,

I don't think the cause is the "3.0" instead of "3" (in the log, you do read "3" and not "3.0", what means the value is well converted).

I cannot reproduce on my device:
<img width="632" alt="Capture d’écran 2024-04-09 à 21 17 57" src="https://github.com/OlivierZal/com.melcloud/assets/88216225/4c223793-d8cd-48ab-820a-975ec0267c1e">

Can you please recreate the card and try again?
If it still does not work, can you join the Homey community Slack (http://slack.athom.com), so we can debug easier?

Kind regards

**Comment by OlivierZal** [comment]
PS: What is your MELCloud app version?

**Comment by OlivierZal** [comment]
@iFac3, same issue, let's track here.

Can you join http://slack.athom.com/ so we can debug together?

**Comment by iFac3** [comment]
Hi Oliver,Replacing the card made the issue done.Thanks!Rgds,G.Az iPademről küldve2024. ápr. 10. dátummal, 16:29 időpontban Olivier Zalmanski ***@***.***> írta:﻿
Closed #383 as completed.
