### ISSUE TITLE
Climate support missing for Mitsubishi Hero 2.0

### ISSUE THREAD

**Issue by Uhedamej** [OlivierZal/com.melcloud#601]
I can’t select to include my Mitsubishi Hero 2.0 LN35 to Homey Climate devices. Otherwise it’s fully functional in Homey.

Climate group works fine for my older Mitsubishi Hero model.

**Comment by OlivierZal** [comment]
Hi @Uhedamej, unfortunately this issue is on Homey side, I even created a ticket (quite a long time ago): https://github.com/athombv/homey-apps-sdk-issues/issues/361

The reason why the old ones appear under climate is that in the meanwhile they created a new class for heat pumps, old devices are still "thermostat" (unless you recreate them). 

Kind regards
