### ISSUE TITLE
Incorrect fan speed displayed

### ISSUE THREAD

**Issue by DavidDjerf** [OlivierZal/com.melcloud#634]
In the Homey device info page, the number for the "current fan speed" is showed as the current fan speed. This seem to be wrong.
Mine always show 1, even when the variable for the "fan speed" is higher.

In the flows, the fan speed is being set in 100%, 200% etc up to 500%. Is this by choice?

![currentfanspeed](https://github.com/user-attachments/assets/db87228e-5394-459b-a842-d53843e4c489)
![fanspeed_1](https://github.com/user-attachments/assets/f67c25ea-9870-4e06-b658-6803c6e437ca)

**Comment by OlivierZal** [comment]
Hi @DavidDjerf

I know, unfortunately it's not an issue with my app but with Homey 2016-2019. 

I filed this issue https://github.com/athombv/homey-apps-sdk-issues/issues/374 some time ago, if you want to follow it...

Kind regards

**Comment by OlivierZal** [comment]
Hi @DavidDjerf 

100%, 200%, etc. in flows and logo display are not issues from my app but from Homey, for which I've filed issues:
- https://github.com/athombv/homey-apps-sdk-issues/issues/374
- https://github.com/athombv/homey-apps-sdk-issues/issues/372

Current fan speed is a value retrieved from the MELCloud API, like all the other values, so if all the other values are good, either this is the _actual_ value of your fan speed (which is theoretically lower or equal to the fan speed _you set_), or the issue comes from MELCloud. 

If want me to check and confirm my diagnostic, you can provide olivier.zalmanski@me.com with a guest access from the official MELCloud mobile or web app (https://app.melcloud.com).

Kind regards
