### ISSUE TITLE
More "When" flowcards

### ISSUE THREAD

**Issue by Exerqtor** [OlivierZal/com.melcloud#69]
Hi, it would be great if there were some "when" cards avalible for "The current was changed" and "The power meter was changed". That output the current and power meter values respectively (like many/most other apps do).

Would love to use it for some unit-specific utility price logging.

**Comment by OlivierZal** [comment]
Hi @Exerqtor 

First of all, do you have an air-to-air or a air-to-water heat pump?

In both cases a lot of ˋwhen` flow cards already exist.

![image](https://user-images.githubusercontent.com/88216225/208013650-36bc6597-42c4-42fa-917f-c7be3265b003.png)

![image](https://user-images.githubusercontent.com/88216225/208013680-a36da398-0f24-4c5b-a844-f5a918ddf758.png)

If you don't see them, you can activate / deactivate the ones you are interested in from device settings.

However flow possibilities are limited not because of the Homey app but because of the MELCloud API, which does not make the live consumption available.

Air-to-air consumption can be retrieved on a hourly basis although air-to-water consumption can be retrieved only on a daily basis.

In the case of the air-to-water, I've added the flow cards but they are quite meaningless since the value will necessarily change every day but without offering you the possibility to adapt your current consumption to current electricity price in an accurate way. 

By the way, I think this discussion is related to your request: https://community.homey.app/t/melcloud/17125/75?u=olivierzal (since then, I've added the hourly consumption for air-to-air).

Last point, if you live in Sweden and have a air-to-water, I know some guy which makes amazing flows related to price optimization based on a Homey electricity app without using consumption flow cards by only adapting temperatures and modes to times and prices. If you're interested I can share you in a private message. 

Does all this answer and address your question and request?

Kind regards

**Comment by OlivierZal** [comment]
Hi @Exerqtor, did I answer your question?

**Comment by OlivierZal** [comment]
I close the issue, @Exerqtor don't hesitate to contact me again for any further question!
