### ISSUE TITLE
Unable to connect 

### ISSUE THREAD

**Issue by Ceklswe** [OlivierZal/com.melcloud#70]
Hi! 
I accidentally removed my heat pump from homey and now it won’t reinstall. I have tried to remove the app and reinstall but nothing seems to work. What am I doing wrong? 

![C8FEB8FF-0443-4208-A8E2-76B4B03A12AE](https://user-images.githubusercontent.com/121514483/209708207-dca0d12b-828f-4b5e-b1c9-cc8812c03308.png)
![5FF10C7B-BFEC-49EE-A319-7D160E83BA5C](https://user-images.githubusercontent.com/121514483/209708234-6a5477ea-f867-4dd1-ac21-bc2498411d14.png)
![531A7AD0-C38F-46FE-A66A-1477594B5B66](https://user-images.githubusercontent.com/121514483/209708243-5ad44cbd-cddc-4e26-98b8-221a0476c5f4.png)

**Comment by OlivierZal** [comment]
Hi @Ceklswe 

Can you please grant an access to olivier.zalmanski@me.com from your official MELCloud account so I can  investigate?

Kind regards

**Comment by OlivierZal** [comment]
Also @Ceklswe, does the issue also occur when trying from a computer (https://my.homey.app)?

**Comment by Ceklswe** [comment]
> Hi @Ceklswe
> 
> Can you please grant an access to [olivier.zalmanski@me.com](mailto:olivier.zalmanski@me.com) from your official MELCloud account so I can investigate?
> 
> Kind regards

Hi! Thank you for such a fast response! I haven’t tried from a computer yet! Will try that tomorrow. You should have an invite now if I manage to it correct :)

**Comment by OlivierZal** [comment]
@Ceklswe, as you can see on the following screenshot there is no issue on my side since I can see your device:

![image](https://user-images.githubusercontent.com/88216225/209720133-03c8de24-22a3-4c53-8fa4-e1477698fd5d.png)

I've already heard that such an issue sometimes happens for Android users but they all succeed in adding their device from a computer, that's why I proposed you to try this way (personally I run on an iOS device). 

I use basic code to search heat pumps so I can't figure out why it could fail depending on the device running Homey...

Please keep me informed if it works or not from a computer!

**Comment by Ceklswe** [comment]
Hi! It didn’t work from the computer. When the app is installed on homey, the desktop doesn’t even show the choices. When I uninstall the app, then the choices shows up. Choosing air to heat pump will then install the app but it’s then stuck. Like it can’t connect. I tried the Nibe app and that connected wanted me to sign in to my nibe account. I wonder if homey still thinks that my old configuration with MELCloud is still active somewhere and that’s why it can’t connect. 

![FDBA3619-3311-43D7-B3FD-A75E9D657C48](https://user-images.githubusercontent.com/121514483/209830624-b1af656e-46fd-4107-bb96-5b0c10d298e2.jpeg)
![7578A6FE-F513-417A-A75E-BCC7539D2688](https://user-images.githubusercontent.com/121514483/209830628-c470a987-75f5-4241-9753-d57f7206837e.jpeg)
![875D8BCD-372F-4854-8F67-D67291CC2ECF](https://user-images.githubusercontent.com/121514483/209830632-281fc2e6-9b9e-48b1-9e45-2c6fc512f71e.jpeg)
![A83F6400-18B1-4F9A-A496-5AA788669F4C](https://user-images.githubusercontent.com/121514483/209830635-361da685-29f4-4590-a9a4-4cef4de049ae.jpeg)
![73BE0962-6C09-4B7F-8FD8-4E57797E7065](https://user-images.githubusercontent.com/121514483/209830641-1fbf721f-291a-491a-bd23-7c4fd22d02fc.png)
![C3CEB0CC-FD30-47D2-8F70-DAD45F9ED188](https://user-images.githubusercontent.com/121514483/209830645-11e664df-51d9-4041-96be-1ce95d6bb3b6.jpeg)

**Comment by OlivierZal** [comment]
Looks like a Homey issue rather than an app one...

Which version if MELCloud do you run? Should be 8.0.7. 

![image](https://user-images.githubusercontent.com/88216225/209837220-683f8c8e-7977-4515-8149-21598dafd5de.png)

**Comment by OlivierZal** [comment]
@Ceklswe, can you try again from your phone and then generate a diagnostic report?

![image](https://user-images.githubusercontent.com/88216225/209842117-098b9b96-5aec-452a-ae03-bfacd29eb214.png)

**Comment by Ceklswe** [comment]
Hi! 
I also think that it has something to do with homey. Here is the crash report

720dcde4-4a27-43d3-8c34-bc0de9ae05dc

**Comment by OlivierZal** [comment]
@Ceklswe, thanks! But as you can see it won't help since it's empty

![image](https://user-images.githubusercontent.com/88216225/209844642-3c701585-05e0-464f-a893-dcad77eecc91.jpeg)

It's like MELCloud was not installed... despite that you see it. 

My advice (even if generally I don't like doing this way): can you please
- check you have no more MELCloud device installed: https://tools.developer.homey.app/tools/devices
- uninstall the MELCloud app
- restart your Homey from https://tools.developer.homey.app/tools/system (it can also be useful if your screenshot me the system information)
- install the MELCloud app again
- try again
- tell me how it goes 😃

**Comment by OlivierZal** [comment]
@Ceklswe,

What make me say it's a issue from Homey is that the app code starts from the login screen just after your last screenshot:

![image](https://user-images.githubusercontent.com/88216225/209849655-955c7c14-8b2d-4961-92c2-af4b48ff3a81.png)

and if I well understand you never reach this step, is that right?

**Comment by Ceklswe** [comment]
Hi!
MELCloud is back! I had to do a reset of the Homey and then use my backup file. After that, there were no issues to install the app and add my pump! Thank you for all of your help!

**Comment by OlivierZal** [comment]
@Ceklswe,

I'm glad to hear! I would be very surprised if it were a MELCloud app issue but whatever the reason the most important to me is to make it work go for every user.
