### ISSUE TITLE
Network request failed during installation

### ISSUE THREAD

**Issue by logchem** [OlivierZal/com.melcloud#74]
When I try to install the MELCloud app on my Homey Pro, I receive the error "Network request failed".
Steps:
- Add new device
- Select MELCloud app
- Select Air-to-Water Heat Pump
- Fill in MelCloud my username and Password
After clicking Connect, waiting... then I receive the message "Network request failed".

Do I need to pre-authorize the app or do something else?
At https://app.melcloud.com/ I can log in and operate the heat pump.

**Comment by OlivierZal** [comment]
Hi @logchem,

No pre-authorisation is needed.
Generally "Network request failed" is not an app issue but a Homey Pro one, and could be solved by restarting the box.

Could you please go to https://app.melcloud.com/ and grant a guest access to olivier.zalmanski@me.com ("restricted permission" = read-only access should be enough) so I can confirm the root cause?

**Comment by logchem** [comment]
Hi @OlivierZal,

Rebooting the Homey didn't help, I still get the same error. 
I've given you read-only access, and I hope this helps you see what's going wrong...

**Comment by OlivierZal** [comment]
@logchem,

Unfortunately I confirm this is not an app issue, as you can see in this screenshot:

![IMG_2042](https://user-images.githubusercontent.com/88216225/210530462-7db98cc6-4822-442d-ad02-8cd332be1339.PNG)

**Comment by OlivierZal** [comment]
@logchem, according to my tests, it's nether a MELCloud nor MELCloud app issue but a Homey Pro issue, which seems to be similar to this one: https://github.com/OlivierZal/com.melcloud/issues/70#issuecomment-1366830881

Could you read how the user solved the issue and tell me if it works?
Otherwise I think you'll need to contact Homey support.

**Comment by logchem** [comment]
Hi @OlivierZal,

I have read issue #70, and it seems to be the same problem
Friday I have a little more time and I will back up the Homey pro and then do a factory reset.
I'll let you know if that fixes the problem

**Comment by OlivierZal** [comment]
@logchem, I was thinking, just in case, can you please try again and then generate a log report which will be sent to me?

See https://github.com/OlivierZal/com.melcloud/issues/70#issuecomment-1366771157

**Comment by OlivierZal** [comment]
Hi @logchem, did Athom solve your issue?

If not, can you try what I adviced in my last comment?

**Comment by logchem** [comment]
> @logchem, I was thinking, just in case, can you please try again and then generate a log report which will be sent to me?
> 
> See [#70 (comment)](https://github.com/OlivierZal/com.melcloud/issues/70#issuecomment-1366771157)

Hi @OlivierZal How can I create and download a log? The only log I can find is the Diagnostics Report that genarates a ID...

**Comment by logchem** [comment]
I found the problem, it was the managed switch :(
I had put the wifi access point directly into the router and it worked immediately :)
Thank you!

**Comment by OlivierZal** [comment]
Great!
